#!/usr/bin/env python3
"""Chinese major names + subcategory data. Imported by CN generators."""

CN_MAJOR_NAMES = {
'Philosophy':'哲学','Logic':'逻辑学','Religious Studies':'宗教学','Ethics':'伦理学',
'Economics':'经济学','Economic Statistics':'经济统计学','National Economics Management':'国民经济管理',
'Resource and Environmental Economics':'资源与环境经济学','Business Economics':'商务经济学',
'Energy Economics':'能源经济','Labor Economics':'劳动经济学','Economic Engineering':'经济工程',
'Digital Economy':'数字经济','Public Finance':'财政学','Taxation':'税收学',
'International Taxation':'国际税收','Finance':'金融学','Financial Engineering':'金融工程',
'Insurance':'保险学','Investment':'投资学','Financial Mathematics':'金融数学',
'Credit Management':'信用管理','Economics and Finance':'经济与金融','Actuarial Science':'精算学',
'Internet Finance':'互联网金融','Financial Technology':'金融科技','Financial Audit':'金融审计',
'International Economics and Trade':'国际经济与贸易','Trade Economy':'贸易经济',
'International Economic Development Cooperation':'国际经济合作',
'Law':'法学','Intellectual Property':'知识产权','Penology':'监狱学',
'Credit Risk Management and Legal Prevention':'信用风险管理与法律防控',
'International Economic and Trade Rules':'国际经贸规则','Judicial Police Science':'司法警察学',
'Community Correction':'社区矫正','Discipline Inspection and Supervision':'纪检监察',
'International Law':'国际法','Forensic Science':'法证学','National Security Studies':'国家安全学',
'Overseas Interests Security':'境外利益安全','Political Science and Public Administration':'政治学与行政学',
'International Politics':'国际政治','Diplomacy':'外交学',
'International Affairs and International Relations':'国际事务与国际关系',
'Philosophy, Politics and Economics':'政治学、经济学与哲学',
'International Organizations and Global Governance':'国际组织与全球治理',
'Sociology':'社会学','Social Work':'社会工作','Anthropology':'人类学',
"Women's Studies":'女性学','Home Economics':'家政学','Gerontology':'老年学',
'Social Policy':'社会政策','Ethnology':'民族学','Scientific Socialism':'科学社会主义',
'History of the Communist Party of China':'中共党史',
'Ideological and Political Education':'思想政治教育','Marxist Theory':'马克思主义理论',
'Trade Union Studies':'工会学','Public Ordering':'治安学','Investigation':'侦查学',
'Border Control Management':'边防管理','Anti-drug Studies':'禁毒学',
'Police Dog Technology':'警犬技术','Economic Crime Investigation':'经济犯罪侦查',
'Border Control Command':'边防指挥','Fire Protection Command':'消防指挥',
'Security Guard Studies':'安全保卫','Public Security Intelligence':'公安情报学',
'Criminology':'犯罪学','Public Security Management':'公安管理学',
'Foreign-related Policing':'涉外警务','Domestic Security':'国内安全保卫',
'Police Command and Tactics':'警务指挥与战术','Technical Investigation':'技术侦查',
'Coast Guard Law Enforcement':'海警执法','Public Security Political Work':'公安政治工作',
'Immigration Management':'移民管理','Entry-Exit Management':'出入境管理',
'Anti-terrorism Policing':'反恐警务','Fire Protection Political Work':'消防政治工作',
'Railway Policing':'铁路警务',
'Education':'教育学','Science Education':'科学教育','Humanities Education':'人文教育',
'Educational Technology':'教育技术学','Arts Education':'艺术教育',
'Preschool Education':'学前教育','Primary Education':'小学教育','Special Education':'特殊教育',
'Chinese Language Education':'华文教育','Educational Rehabilitation':'教育康复学',
'Health Education':'健康教育','Cognitive Science and Technology':'认知科学与技术',
'Inclusive Education':'融合教育','Labor Education':'劳动教育','Family Education':'家庭教育',
'Autism Education':'孤独症教育','Physical Education':'体育教育','Sports Training':'运动训练',
'Social Sports Guidance and Management':'社会体育指导与管理',
'Wushu and Traditional Ethnic Sports':'武术与民族传统体育','Kinesiology':'运动人体科学',
'Sports Rehabilitation':'运动康复','Leisure Sports':'休闲体育',
'Physical Training':'体能训练','Ice and Snow Sports':'冰雪运动',
'E-Sports and Management':'电子竞技运动与管理','Intelligent Sports Engineering':'智能体育工程',
'Sports Tourism':'体育旅游','Sports Ability Development':'体育运动能力开发',
'Football Sports':'足球运动','Equestrian Sports and Management':'马术运动与管理',
'Sports Wellness':'体育健康管理',
'Chinese Language and Literature':'汉语言文学','Chinese Language':'汉语言',
'Teaching Chinese to Speakers of Other Languages':'汉语国际教育',
'Chinese Ethnic Minority Languages and Literatures':'中国少数民族语言文学',
'Classical Philology':'古典文献学','Applied Linguistics':'应用语言学',
'Secretarial Science':'秘书学','Chinese Language and Culture':'汉语言文化学',
'Sign Language Interpreting':'手语翻译','Digital Humanities':'数字人文',
'Chinese Classics':'国学','Sinology and Chinese Studies':'汉学与中国学','Applied Chinese':'实用汉语',
'English':'英语','Russian':'俄语','German':'德语','French':'法语','Spanish':'西班牙语',
'Arabic':'阿拉伯语','Japanese':'日语','Persian':'波斯语','Korean':'朝鲜语',
'Filipino':'菲律宾语','Sanskrit and Pali':'梵语和巴利语','Indonesian':'印度尼西亚语',
'Hindi':'印地语','Cambodian':'柬埔寨语','Lao':'老挝语','Burmese':'缅甸语','Malay':'马来语',
'Mongolian':'蒙古语','Sinhalese':'僧伽罗语','Thai':'泰语','Urdu':'乌尔都语',
'Hebrew':'希伯来语','Vietnamese':'越南语','Hausa':'豪萨语','Swahili':'斯瓦希里语',
'Albanian':'阿尔巴尼亚语','Bulgarian':'保加利亚语','Polish':'波兰语','Czech':'捷克语',
'Slovak':'斯洛伐克语','Romanian':'罗马尼亚语','Portuguese':'葡萄牙语','Swedish':'瑞典语',
'Serbian':'塞尔维亚语','Turkish':'土耳其语','Greek':'希腊语','Hungarian':'匈牙利语',
'Italian':'意大利语','Tamil':'泰米尔语','Pashto':'普什图语','Esperanto':'世界语',
'Bengali':'孟加拉语','Nepali':'尼泊尔语','Croatian':'克罗地亚语','Dutch':'荷兰语',
'Finnish':'芬兰语','Ukrainian':'乌克兰语','Norwegian':'挪威语','Danish':'丹麦语',
'Icelandic':'冰岛语','Irish':'爱尔兰语','Latvian':'拉脱维亚语','Lithuanian':'立陶宛语',
'Slovenian':'斯洛文尼亚语','Estonian':'爱沙尼亚语','Maltese':'马耳他语',
'Kazakh':'哈萨克语','Uzbek':'乌兹别克语','Zulu':'祖鲁语','Latin':'拉丁语',
'Translation':'翻译','Business English':'商务英语','Amharic':'阿姆哈拉语',
'Kyrgyz':'柯尔克孜语','Somali':'索马里语','Turkmen':'土库曼语','Catalan':'加泰罗尼亚语',
'Yoruba':'约鲁巴语','Armenian':'亚美尼亚语','Malagasy':'马达加斯加语',
'Georgian':'格鲁吉亚语','Azerbaijani':'阿塞拜疆语','Afrikaans':'南非荷兰语',
'Macedonian':'马其顿语','Tajik':'塔吉克语','Tswana':'茨瓦纳语','Ndebele':'恩德贝莱语',
'Comorian':'科摩罗语','Creole':'克里奥尔语','Shona':'绍纳语','Tigrinya':'提格利尼亚语',
'Belarusian':'白俄罗斯语','Maori':'毛利语','Tongan':'汤加语','Samoan':'萨摩亚语',
'Kurdish':'库尔德语','Bislama':'比斯拉马语','Dari':'达里语','Tetum':'德顿语',
'Divehi':'迪维希语','Fijian':'斐济语','Cook Islands Maori':'库克岛毛利语',
'Kirundi':'基隆迪语','Luxembourgish':'卢森堡语','Kinyarwanda':'卢旺达语','Niuean':'纽埃语',
'Tok Pisin':'托克皮辛语','Chewa':'齐切瓦语','Sesotho':'南索托语','Sango':'桑戈语',
'Linguistics':'语言学','Tamazight':'塔马齐格特语','Javanese':'爪哇语','Punjabi':'旁遮普语',
'Journalism':'新闻学','Radio and Television Science':'广播电视学','Advertising':'广告学',
'Communication Studies':'传播学','Editing and Publishing':'编辑出版学',
'Network and New Media':'网络与新媒体','Digital Publishing':'数字出版',
'Fashion Communication':'时尚传播','International Journalism and Communication':'国际新闻与传播',
'Exhibitions and Events':'会展',
'History':'历史学','World History':'世界史','Archaeology':'考古学',
'Cultural Heritage and Museology':'文物与博物馆学','Cultural Relics Preservation Technology':'文物保护技术',
'Foreign Languages and Foreign History':'外国语言与外国历史','Cultural Heritage':'文化遗产',
'Paleography':'古文字学','History of Science':'科学史',
'Mathematics and Applied Mathematics':'数学与应用数学','Information and Computing Science':'信息与计算科学',
'Mathematical and Physical Foundations':'数学与物理学基础','Data Computation and Application':'数据计算及应用',
'Physics':'物理学','Applied Physics':'应用物理学','Nuclear Physics':'核物理','Acoustics':'声学',
'Systems Science and Engineering':'系统科学与工程','Quantum Information Science':'量子信息科学',
'Chemistry':'化学','Applied Chemistry':'应用化学','Chemical Biology':'化学生物学',
'Molecular Science and Engineering':'分子科学与工程','Energy Chemistry':'能源化学',
'Chemical Measurement and Technology':'化学测量学与技术','Resource Chemistry':'资源化学',
'Astronomy':'天文学','Geographical Sciences':'地理科学',
'Physical Geography and Resource Environment':'自然地理与资源环境',
'Human Geography and Urban-Rural Planning':'人文地理与城乡规划',
'Geographic Information Science':'地理信息科学','Atmospheric Sciences':'大气科学',
'Applied Meteorology':'应用气象学','Meteorological Technology and Engineering':'气象技术与工程',
'Earth System Science':'地球系统科学','Marine Sciences':'海洋科学','Marine Technology':'海洋技术',
'Marine Resources and Environment':'海洋资源与环境','Military Oceanography':'军事海洋学',
'Geophysics':'地球物理学','Space Science and Technology':'空间科学与技术',
'Disaster Prevention and Mitigation Science and Engineering':'防灾减灾科学与工程',
'Planetary Science':'行星科学','Geology':'地质学','Geochemistry':'地球化学',
'Geographic Information Science and Technology':'地理信息科学与技术','Paleontology':'古生物学',
'Biological Sciences':'生物科学','Biotechnology':'生物技术','Bioinformatics':'生物信息学',
'Ecology':'生态学','Integrated Science':'综合理科','Neuroscience':'神经科学',
'Psychology':'心理学','Applied Psychology':'应用心理学','Statistics':'统计学',
'Applied Statistics':'应用统计学','Data Science':'数据科学','Biostatistics':'生物统计学',
'Theoretical and Applied Mechanics':'理论与应用力学','Engineering Mechanics':'工程力学',
'Mechanical Engineering':'机械工程','Mechanical Design, Manufacturing and Automation':'机械设计制造及其自动化',
'Materials Forming and Control Engineering':'材料成型及控制工程','Mechatronic Engineering':'机电工程',
'Industrial Design':'工业设计','Process Equipment and Control Engineering':'过程装备与控制工程',
'Vehicle Engineering':'车辆工程','Automobile Service Engineering':'汽车服务工程',
'Mechanical Process Technology':'机械工艺技术',
'Microelectromechanical Systems Engineering':'微机电系统工程',
'Mechatronic Technology Education':'机电技术教育',
'Automotive Maintenance Engineering Education':'汽车维修工程教育',
'Intelligent Manufacturing Engineering':'智能制造工程','Intelligent Vehicle Engineering':'智能车辆工程',
'Bionic Science and Engineering':'仿生科学与工程','New Energy Vehicle Engineering':'新能源汽车工程',
'Additive Manufacturing Engineering':'增材制造工程','Intelligent Interaction Design':'智能交互设计',
'Emergency Equipment Technology and Engineering':'应急装备技术与工程',
'Agricultural and Forestry Intelligent Equipment Engineering':'农林智能装备工程',
'Measurement and Control Technology and Instruments':'测控技术与仪器',
'Precision Instruments':'精密仪器','Intelligent Perception Engineering':'智能感知工程',
'Materials Science and Engineering':'材料科学与工程','Materials Physics':'材料物理',
'Materials Chemistry':'材料化学','Metallurgical Engineering':'冶金工程',
'Metallic Materials Engineering':'金属材料工程',
'Inorganic Non-metallic Materials Engineering':'无机非金属材料工程',
'Macromolecular Materials and Engineering':'高分子材料与工程',
'Composite Materials and Engineering':'复合材料与工程',
'Powder Materials Science and Engineering':'粉体材料科学与工程',
'Gemology and Material Technology':'宝石及材料工艺学',
'Welding Technology and Engineering':'焊接技术与工程','Functional Materials':'功能材料',
'Nanomaterials and Technology':'纳米材料与技术','New Energy Materials and Devices':'新能源材料与器件',
'Materials Design Science and Engineering':'材料设计科学与工程',
'Composite Materials Molding Engineering':'复合材料成型工程',
'Intelligent Materials and Structures':'智能材料与结构',
'Optoelectronic Information Materials and Devices':'光电信息材料与器件',
'Biomaterials':'生物材料','Intelligent Materials Technology':'智能材料技术',
'Electronic Information Materials':'电子信息材料','Soft Matter Science and Engineering':'软物质科学与工程',
'Rare Earth Materials Science and Engineering':'稀土材料科学与工程',
'Energy and Power Engineering':'能源与动力工程',
'Energy and Environmental Systems Engineering':'能源与环境系统工程',
'New Energy Science and Engineering':'新能源科学与工程',
'Energy Storage Science and Engineering':'储能科学与工程',
'Energy Service Engineering':'能源服务工程','Hydrogen Energy Science and Engineering':'氢能科学与工程',
'Sustainable Energy':'可持续能源','Electrical Engineering and Automation':'电气工程及其自动化',
'Smart Grid Information Engineering':'智能电网信息工程','Light Sources and Illumination':'光源与照明',
'Electrical Engineering and Intelligent Control':'电气工程与智能控制',
'Intelligent Motor and Electrical Apparatus':'智能电机与电气装置','Cable Engineering':'电缆工程',
'Energy Internet Engineering':'能源互联网工程','Smart Energy Engineering':'智慧能源工程',
'Electric Transportation Engineering':'电气交通工程',
'High-Power Semiconductor Science and Engineering':'大功率半导体科学与工程',
'Electronic and Information Engineering':'电子信息工程',
'Electronic Science and Technology':'电子科学与技术','Communication Engineering':'通信工程',
'Microelectronic Science and Engineering':'微电子科学与工程',
'Optoelectronic Information Science and Engineering':'光电信息科学与工程',
'Information Engineering':'信息工程','Radio and Television Engineering':'广播电视工程',
'Underwater Acoustic Engineering':'水声工程','Electronic Packaging Technology':'电子封装技术',
'Integrated Circuit Design and Integrated System':'集成电路设计与集成系统',
'Medical Information Engineering':'医学信息工程',
'Electromagnetic Field and Wireless Technology':'电磁场与无线技术',
'Radio Wave Propagation and Antenna':'电波传播与天线',
'Electronic Information Science and Technology':'电子信息科学与技术',
'Telecommunications Engineering and Management':'电信工程及管理',
'Applied Electronic Technology Education':'应用电子技术教育','Artificial Intelligence':'人工智能',
'Marine Information Engineering':'海洋信息工程','Flexible Electronics':'柔性电子学',
'Intelligent Measurement and Control Engineering':'智能测控工程',
'Intelligent Vision Engineering':'智能视觉工程','Automation':'自动化',
'Rail Traffic Signal and Control':'轨道交通信号与控制','Robotics Engineering':'机器人工程',
'Postal Engineering':'邮政工程','Nuclear Power Technology and Control Engineering':'核电技术与控制工程',
'Intelligent Equipment and Systems':'智能装备与系统','Industrial Intelligence':'工业智能',
'Intelligent Engineering and Creative Design':'智能工程创意设计',
'Computer Science and Technology':'计算机科学与技术','Software Engineering':'软件工程',
'Network Engineering':'网络工程','Information Security':'信息安全',
'Internet of Things Engineering':'物联网工程','Digital Media Technology':'数字媒体技术',
'Intelligent Science and Technology':'智能科学与技术',
'Spatial Information and Digital Technology':'空间信息与数字技术',
'Electronic and Computer Engineering':'电子与计算机工程',
'Data Science and Big Data Technology':'数据科学与大数据技术',
'Cyberspace Security':'网络空间安全','New Media Technology':'新媒体技术',
'Film Production':'影视摄制','Secrecy Technology':'保密技术',
'Service Science and Engineering':'服务科学与工程','Virtual Reality Technology':'虚拟现实技术',
'Blockchain Engineering':'区块链工程','Cryptography Science and Technology':'密码科学与技术',
'Civil Engineering':'土木工程','Building Environment and Energy Engineering':'建筑环境与能源应用工程',
'Water Supply and Drainage Science and Engineering':'给排水科学与工程',
'Building Electricity and Intelligence':'建筑电气与智能化',
'Urban Underground Space Engineering':'城市地下空间工程',
'Road, Bridge and River-crossing Engineering':'道路桥梁与渡河工程',
'Railway Engineering':'铁道工程','Intelligent Construction':'智能建造',
'Civil, Hydraulic and Marine Engineering':'土木、水利与海洋工程',
'Civil, Hydraulic and Transportation Engineering':'土木、水利与交通工程',
'Urban Water System Engineering':'城市水系统工程',
'Intelligent Construction and Smart Transportation':'智能建造与智慧交通',
'Engineering Software':'工程软件','Hydraulic and Hydroelectric Engineering':'水利水电工程',
'Hydrology and Water Resources Engineering':'水文与水资源工程',
'Port, Coastal and Ocean Engineering':'港口航道与海岸工程','Water Affairs Engineering':'水务工程',
'Hydraulic Science and Engineering':'水利科学与工程','Smart Water Conservancy':'智慧水利',
'Geomatics Engineering':'测绘工程','Remote Sensing Science and Technology':'遥感科学与技术',
'Navigation Engineering':'导航工程','Geographical Condition Monitoring':'地理国情监测',
'Geospatial Information Engineering':'地理空间信息工程',
'Chemical Engineering and Technology':'化学工程与工艺','Pharmaceutical Engineering':'制药工程',
'Resource Circulation Science and Engineering':'资源循环科学与工程',
'Energy Chemical Engineering':'能源化学工程',
'Chemical Engineering and Industrial Bioengineering':'化学工程与工业生物工程',
'Chemical Safety Engineering':'化学安全工程','Coating Engineering':'涂装工程',
'Fine Chemicals':'精细化工','Geological Engineering':'地质工程',
'Exploration Technology and Engineering':'勘查技术与工程',
'Resource Exploration Engineering':'资源勘查工程',
'Groundwater Science and Engineering':'地下水科学与工程',
'Tourism Earth Science and Planning Engineering':'旅游地学与规划工程',
'Intelligent Earth Exploration':'智能地球探测',
'Resource and Environment Big Data Engineering':'资源与环境大数据工程',
'Mining Engineering':'采矿工程','Petroleum Engineering':'石油工程',
'Mineral Processing Engineering':'矿物加工工程',
'Oil and Gas Storage and Transportation Engineering':'油气储运工程',
'Mineral Resources Engineering':'矿业资源工程','Offshore Oil and Gas Engineering':'海洋油气工程',
'Intelligent Mining Engineering':'智能采矿工程','Carbon Storage Science and Engineering':'碳储科学与工程',
'Textile Engineering':'纺织工程','Apparel Design and Engineering':'服装设计与工程',
'Non-woven Materials and Engineering':'非织造材料与工程',
'Apparel Design and Technology Education':'服装设计与技术教育',
'Silk Design and Engineering':'丝绸设计与工程','Light Chemical Engineering':'轻化工程',
'Packaging Engineering':'包装工程','Printing Engineering':'印刷工程',
'Flavor and Fragrance Technology and Engineering':'香料香精技术与工程',
'Cosmetics Technology and Engineering':'化妆品技术与工程',
'Biomass Energy and Materials':'生物质能源与材料',
'Traffic and Transportation':'交通运输','Traffic Engineering':'交通工程',
'Navigation Technology':'航海技术','Marine Engineering':'轮机工程','Aviation Technology':'飞行技术',
'Traffic Equipment and Control Engineering':'交通设备与控制工程',
'Rescue and Salvage Engineering':'救助与打捞工程',
'Marine Electronic and Electrical Engineering':'船舶电子电气工程',
'Rail Transit Electrification and Control':'轨道交通电气化与控制',
'Cruise Engineering and Management':'邮轮工程与管理','Smart Transportation':'智慧交通',
'Intelligent Transportation Engineering':'智能交通工程',
'Naval Architecture and Ocean Engineering':'船舶与海洋工程',
'Ocean Engineering and Technology':'海洋工程与技术',
'Marine Resource Development Technology':'海洋资源开发技术',
'Marine Robotics':'海洋机器人','Smart Ocean Technology':'智能海洋技术',
'Intelligent Marine Equipment':'智能海洋装备','Aerospace Engineering':'航空航天工程',
'Flight Vehicle Design and Engineering':'飞行器设计与工程',
'Flight Vehicle Manufacturing Engineering':'飞行器制造工程',
'Flight Vehicle Power Engineering':'飞行器动力工程',
'Flight Vehicle Environment and Life Support Engineering':'飞行器环境与生命保障工程',
'Flight Vehicle Quality and Reliability':'飞行器质量与可靠性',
'Flight Vehicle Airworthiness Technology':'飞行器适航技术',
'Flight Vehicle Control and Information Engineering':'飞行器控制与信息工程',
'Unmanned Aerial Vehicle Systems Engineering':'无人驾驶航空器系统工程',
'Intelligent Flight Vehicle Technology':'智能飞行器技术',
'Aerospace Intelligent Electric Propulsion Technology':'航空航天智能电推进技术',
'Flight Vehicle Operation and Maintenance Engineering':'飞行器运维工程',
'Weapon Systems and Engineering':'武器系统与工程','Weapon Launching Engineering':'武器发射工程',
'Detection, Guidance and Control Technology':'探测制导与控制技术',
'Ammunition Engineering and Explosive Technology':'弹药工程与爆炸技术',
'Special Energy Technology and Engineering':'特种能源技术与工程',
'Armored Vehicle Engineering':'装甲车辆工程','Information Countermeasure Technology':'信息对抗技术',
'Intelligent Unmanned Systems Technology':'智能无人系统技术',
'Nuclear Engineering and Technology':'核工程与核技术',
'Radiation Protection and Nuclear Safety':'辐射防护与核安全',
'Engineering Physics':'工程物理','Nuclear Chemical and Fuel Engineering':'核化工与核燃料工程',
'Agricultural Engineering':'农业工程','Agricultural Mechanization and Automation':'农业机械化及其自动化',
'Agricultural Electrification':'农业电气化',
'Agricultural Building Environment and Energy Engineering':'农业建筑环境与能源工程',
'Agricultural Water Conservancy Engineering':'农业水利工程',
'Land Consolidation Engineering':'土地整治工程',
'Intelligent Agricultural Equipment Engineering':'智慧农业装备工程',
'Forest Engineering':'森林工程','Wood Science and Engineering':'木材科学与工程',
'Chemical Processing of Forest Products':'林产化工','Furniture Design and Engineering':'家具设计与工程',
'Timber Structure Architecture and Materials':'木结构建筑与材料',
'Environmental Science and Engineering':'环境科学与工程','Environmental Engineering':'环境工程',
'Environmental Science':'环境科学','Environmental Ecological Engineering':'环境生态工程',
'Environmental Protection Equipment Engineering':'环保设备工程',
'Resource and Environmental Science':'资源与环境科学','Water Quality Science and Technology':'水质科学与技术',
'Biomedical Engineering':'生物医学工程','Prosthetics and Orthotics Engineering':'假肢矫形工程',
'Clinical Engineering Technology':'临床工程技术','Rehabilitation Engineering':'康复工程',
'Health Science and Technology':'健康科学与技术','Food Science and Engineering':'食品科学与工程',
'Food Quality and Safety':'食品质量与安全','Grain Engineering':'粮食工程',
'Dairy Engineering':'乳品工程','Wine-making Engineering':'酿酒工程',
'Viticulture and Enology Engineering':'葡萄与葡萄酒工程',
'Food Nutrition and Inspection Education':'食品营养与检验教育',
'Culinary and Nutrition Education':'烹饪与营养教育','Food Safety and Testing':'食品安全与检测',
'Food Nutrition and Health':'食品营养与健康','Edible Fungi Science and Engineering':'食用菌科学与工程',
'Liquor Brewing Engineering':'白酒酿造工程','Coffee Science and Engineering':'咖啡科学与工程',
'Architecture':'建筑学','Urban and Rural Planning':'城乡规划','Landscape Architecture':'风景园林',
'Historic Building Protection Engineering':'历史建筑保护工程',
'Human Settlement Science and Technology':'人居环境科学与技术','Urban Design':'城市设计',
'Smart Architecture and Construction':'智慧建筑与建造','Safety Engineering':'安全工程',
'Emergency Technology and Management':'应急技术与管理',
'Occupational Health Engineering':'职业卫生工程',
'Safety Production Supervision':'安全生产监管','Bioengineering':'生物工程',
'Biopharmaceutical':'生物制药','Synthetic Biology':'合成生物学',
'Criminal Science and Technology':'刑事科学技术','Fire Protection Engineering':'消防工程',
'Traffic Management Engineering':'交通管理工程','Security Engineering':'安全防范工程',
'Public Security Audio-Visual Technology':'公安视听技术',
'Rescue Command and Technology':'抢险救援指挥与技术','Fire Investigation':'火灾调查',
'Network Security and Law Enforcement':'网络安全与执法',
'Nuclear, Biological and Chemical Firefighting':'核生化消防',
'Coast Guard Vessel Command and Technology':'海警舰艇指挥与技术',
'Data Policing Technology':'数字警务技术',
'Food, Drug and Environmental Crime Investigation Technology':'食品药品与环境犯罪侦查技术',
'Future Robotics':'未来机器人','Cross-disciplinary Engineering':'跨学科工程',
'Agronomy':'农学','Horticulture':'园艺','Plant Protection':'植物保护',
'Plant Science and Technology':'植物科学与技术','Seed Science and Engineering':'种子科学与工程',
'Protected Agriculture Science and Engineering':'设施农业科学与工程','Tea Science':'茶学',
'Tobacco Science':'烟草学','Applied Biological Sciences':'应用生物科学',
'Agronomy Education':'农学教育','Horticulture Education':'园艺教育','Smart Agriculture':'智慧农业',
'Mycology Science and Engineering':'菌物科学与工程','Pesticides and Fertilizers':'农药与肥料',
'Biopesticide Science and Engineering':'生物农药科学与工程',
'Biological Breeding Science':'生物育种科学','Biological Breeding Technology':'生物育种技术',
'Agricultural Resources and Environment':'农业资源与环境',
'Wildlife and Nature Reserve Management':'野生动物与自然保护区管理',
'Soil and Water Conservation and Desertification Control':'水土保持与荒漠化防治',
'Biomass Science and Engineering':'生物质科学与工程','Land Science and Technology':'土地科学与技术',
'Wetland Protection and Restoration':'湿地保护与恢复',
'National Park Construction and Management':'国家公园建设与管理',
'Ecological Restoration':'生态修复','Animal Science':'动物科学','Sericulture':'蚕学',
'Apiculture':'蜂学','Economic Zoology':'经济动物学','Equine Science':'马业科学',
'Feed Engineering':'饲料工程','Smart Animal Husbandry Science and Engineering':'智慧畜牧业科学与工程',
'Veterinary Medicine':'动物医学','Veterinary Pharmacy':'动物药学',
'Animal and Plant Quarantine':'动植物检疫','Laboratory Animal Science':'实验动物学',
'Traditional Chinese Veterinary Medicine':'中兽医学','Veterinary Public Health':'兽医公共卫生',
'Forestry':'林学','Landscape Architecture (Forestry)':'园林','Forest Protection':'森林保护',
'Economic Forest':'经济林','Smart Forestry':'智慧林业','Aquaculture':'水产养殖学',
'Marine Fishery Science and Technology':'海洋渔业科学与技术',
'Aquarium Science and Technology':'水族科学与技术','Aquatic Animal Medicine':'水生动物医学',
'Pratacultural Science':'草业科学','Turfgrass Science and Engineering':'草坪草科学与工程',
'Basic Medicine':'基础医学','Biomedical Sciences':'生物医学科学','Clinical Medicine':'临床医学',
'Anesthesiology':'麻醉学','Medical Imaging':'医学影像学','Optometry Medicine':'眼视光医学',
'Psychiatry':'精神医学','Radiation Medicine':'放射医学','Pediatrics':'儿科学',
'Stomatology':'口腔医学','Preventive Medicine':'预防医学',
'Food Hygiene and Nutrition':'食品卫生与营养学','Maternal and Child Health Medicine':'妇幼保健医学',
'Health Supervision':'卫生监督','Global Health':'全球健康学','Sports and Public Health':'运动与公共健康',
'Traditional Chinese Medicine':'中医学','Acupuncture, Moxibustion and Tuina':'针灸推拿学',
'Tibetan Medicine':'藏医学','Mongolian Medicine':'蒙医学','Uyghur Medicine':'维医学',
'Zhuang Medicine':'壮医学','Kazakh Medicine':'哈医学','Dai Medicine':'傣医学',
'Hui Medicine':'回医学','Traditional Chinese Medicine Rehabilitation':'中医康复学',
'Traditional Chinese Medicine Health Preservation':'中医养生学',
'Traditional Chinese Medicine Pediatrics':'中医儿科学',
'Traditional Chinese Medicine Orthopedics and Traumatology':'中医骨伤科学',
'Integrated Traditional Chinese and Western Clinical Medicine':'中西医临床医学',
'Pharmacy':'药学','Pharmaceutics':'药物制剂','Clinical Pharmacy':'临床药学',
'Pharmaceutical Affairs Management':'药事管理','Pharmaceutical Analysis':'药物分析',
'Medicinal Chemistry':'药物化学','Marine Pharmacy':'海洋药学',
'Cosmetic Science and Technology':'化妆品科学与技术','Chinese Materia Medica':'中药学',
'Chinese Materia Medica Resource and Development':'中药资源与开发','Tibetan Pharmacy':'藏药学',
'Mongolian Pharmacy':'蒙药学','Chinese Materia Medica Pharmaceutics':'中药制药',
'Chinese Medicinal Herb Cultivation and Identification':'中草药栽培与鉴定',
'Forensic Medicine':'法医学','Medical Laboratory Technology':'医学检验技术',
'Medical Experimental Technology':'医学实验技术','Medical Imaging Technology':'医学影像技术',
'Optometry':'眼视光学','Rehabilitation Therapeutics':'康复治疗学',
'Stomatological Medical Technology':'口腔医学技术',
'Sanitary Inspection and Quarantine':'卫生检验与检疫',
'Audiology and Speech Rehabilitation':'听力与言语康复学',
'Rehabilitation Physical Therapy':'康复物理治疗','Rehabilitation Occupational Therapy':'康复作业治疗',
'Intelligent Medical Engineering':'智能医学工程','Biomedical Data Science':'生物医学数据科学',
'Intelligent Imaging Engineering':'智能影像工程','Medical Engineering':'医学工程',
'Nursing':'护理学','Midwifery':'助产学',
'Management Science':'管理科学','Information Management and Information Systems':'信息管理与信息系统',
'Engineering Management':'工程管理','Real Estate Development and Management':'房地产开发与管理',
'Engineering Cost':'工程造价','Secrecy Management':'保密管理','Postal Management':'邮政管理',
'Big Data Management and Application':'大数据管理与应用','Engineering Auditing':'工程审计',
'Computational Finance':'算法与计算金融','Emergency Management':'应急管理',
'Business Administration':'工商管理','Marketing':'市场营销','Accounting':'会计学',
'Financial Management':'财务管理','International Business':'国际商务',
'Human Resource Management':'人力资源管理','Auditing':'审计学','Asset Appraisal':'资产评估',
'Property Management':'物业管理','Cultural Industry Management':'文化产业管理',
'Labor Relations':'劳动关系','Sports Economics and Management':'体育经济与管理',
'Financial Accounting Education':'财务会计教育','Marketing Education':'市场营销教育',
'Retail Management':'零售管理','Entrepreneurship Management':'创业管理',
'Customs Audit':'海关稽查','Internal Auditing':'内部审计',
'Agricultural and Forestry Economics Management':'农林经济管理',
'Rural Regional Development':'农村区域发展','Rural Governance':'乡村振兴',
'Public Utility Management':'公共事业管理','Administrative Management':'行政管理',
'Labor and Social Security':'劳动与社会保障','Land Resource Management':'土地资源管理',
'Urban Management':'城市管理','Customs Management':'海关管理',
'Traffic Management':'交通管理','Maritime Management':'海事管理','Public Relations':'公共关系',
'Health Service and Management':'健康服务与管理',
'Coast Guard Logistics Management':'海警后勤管理','Medical Product Management':'医疗产品管理',
'Medical Insurance':'医疗保险','Elderly Care Service Management':'老年服务与管理',
'Customs Inspection and Quarantine Safety':'海关稽查与查验安全',
'Overseas Security Management':'境外安全管理',
'Natural Resource Registration and Management':'自然资源登记与管理',
'Philanthropy Management':'公益慈善管理','Aviation Security Management':'航空安全保卫',
'Accessibility Management':'无障碍管理','Library Science':'图书馆学','Archival Science':'档案学',
'Information Resource Management':'信息资源管理','Logistics Management':'物流管理',
'Logistics Engineering':'物流工程','Purchasing Management':'采购管理',
'Supply Chain Management':'供应链管理','Industrial Engineering':'工业工程',
'Standardization Engineering':'标准化工程','Quality Management Engineering':'质量管理工程',
'E-commerce':'电子商务','E-commerce and Law':'电子商务及法律',
'Cross-border E-commerce':'跨境电子商务','Tourism Management':'旅游管理',
'Hospitality Management':'酒店管理',
}

CN_CAT = {
'Philosophy':'哲学','Economics':'经济学','Law':'法学','Education':'教育学',
'Literature':'文学','History':'历史学','Science':'理学','Engineering':'工学',
'Agriculture':'农学','Medicine':'医学','Management':'管理学',
}

CN_SUB = {
'Philosophy':'哲学','Economics':'经济学','Finance':'金融学',
'International Economics & Trade / Public Finance':'国际经济与财政',
'Sociology':'社会学','Political Science':'政治学','Ethnology':'民族学',
'Marxist Theory':'马克思主义理论','Public Security':'公安学',
'Education':'教育学','Physical Education':'体育学',
'Chinese Language & Lit':'汉语言文学','Foreign Languages':'外国语言文学',
'Journalism & Comm':'新闻传播学','History':'历史学','Mathematics':'数学','Physics':'物理学',
'Chemistry':'化学','Astronomy':'天文学','Geographic Sciences':'地理科学',
'Atmospheric Sciences':'大气科学','Marine Sciences':'海洋科学','Geophysics':'地球物理学',
'Geology':'地质学','Biological Sciences':'生物科学','Psychology':'心理学','Statistics':'统计学',
'Mechanics':'力学','Mechanical Engineering':'机械类','Instrumentation':'仪器类',
'Materials Science':'材料类','Energy & Power':'能源动力类','Electrical Engineering':'电气类',
'Electronic Information':'电子信息类','Automation':'自动化类','Computer Science':'计算机类',
'Civil Engineering':'土木类','Hydraulic Engineering':'水利类','Surveying & Mapping':'测绘类',
'Chem Engineering & Pharmacy':'化工与制药类','Geological Engineering':'地质类',
'Mining':'矿业类','Textile':'纺织类','Light Industry':'轻工类',
'Transportation':'交通运输类','Ocean Engineering':'海洋工程类','Aerospace':'航空航天类',
'Ordnance':'兵器类','Nuclear Engineering':'核工程类','Agricultural Engineering':'农业工程类',
'Forestry Engineering':'林业工程类','Environmental Engineering':'环境类',
'Biomedical Engineering':'生物医学工程类','Food Science & Engineering':'食品科学与工程类',
'Architecture':'建筑类','Safety Engineering':'安全科学与工程类',
'Biological Sciences (Eng)':'生物工程类','Public Security Tech':'公安技术类',
'Interdisciplinary Eng':'交叉工程类','Agronomy':'植物生产类',
'Agricultural Management':'自然保护与环境生态类','Animal Production':'动物生产类',
'Veterinary Medicine':'动物医学类','Forestry':'林学类','Fisheries':'水产类',
'Grassland Science':'草学类','Basic Medical Sciences':'基础医学类',
'Clinical Medicine':'临床医学类','Stomatology':'口腔医学类','Public Health':'公共卫生与预防医学类',
'Trad. Chinese Medicine':'中医学类','Integrative Medicine':'中西医结合类',
'Pharmacy':'药学类','Chinese Materia Medica':'中药学类','Forensic Medicine':'法医学类',
'Medical Technology':'医学技术类','Nursing':'护理学类',
'Management Sci & Eng':'管理科学与工程类','Business Administration':'工商管理类',
'Agricultural Management (Mgmt)':'农业经济管理类','Public Administration':'公共管理类',
'Library & Info Management':'图书情报与档案管理类','Logistics Management':'物流管理类',
'Industrial Engineering':'工业工程类','E-Commerce':'电子商务类',
'Tourism Management':'旅游管理类',
}

# Subcategory Chinese pros/cons (88 entries)
CN_SUBCAT = {
'Advanced Engineering':{
    'pros':['承担国家重大科技攻关任务，职业使命感强','掌握尖端技术，在国防航空等行业具有不可替代性','薪资待遇优厚，科研经费充足'],
    'cons':['准入门槛极高，竞争仅限顶尖院校','部分岗位涉及保密要求，职业路径相对固定','实验周期长，短期内难见明显成果'],
    'verdict':'顶尖工程专业，国家战略需求强劲，适合立志深耕高端技术领域的学生。'},
'Aerospace':{
    'pros':['国家战略性产业，政策资源倾斜明显','技术含量高，工程师社会地位较高','参与大国重器项目，职业自豪感强'],
    'cons':['就业集中于少数央企及科研院所，选择面窄','毕业薪资增速较慢，晋升靠年资积累','部分岗位需长期驻扎偏远试验基地'],
    'verdict':'航空航天是国之重器。人才缺口大，但就业路径相对单一，适合有国防科技情怀的学生。'},
'Agricultural Engineering':{
    'pros':['农业现代化战略带动，专业价值快速提升','智慧农业转型下，交叉型人才极度稀缺','粮食安全战略高度，政策资源持续投入'],
    'cons':['行业薪资相对较低，一线岗位工作条件艰苦','乡村就业环境与城市落差大','就业地点多在欠发达地区'],
    'verdict':'农业装备现代化的关键专业。政策红利明显，但需要做好在农村工作的心理准备。'},
'Agricultural Management':{
    'pros':['乡村振兴政策带来大量管理岗位','农业产业链整合下，复合型人才需求旺盛','可走农业+互联网新农业创业路线'],
    'cons':['传统路径薪资偏低','就业地点多在县乡，生活条件有限','需持续学习新农技才能保持竞争力'],
    'verdict':'乡村振兴大背景下有政策红利，但薪资和生活条件是现实考量。适合有农业情怀、愿意扎根基层的学生。'},
'Animal Production':{
    'pros':['肉蛋奶等食品安全需求稳定，就业有保障','现代化牧场和养殖集团管理需求持续增长','兽药、饲料等产业链机会多样'],
    'cons':['工作环境差，体力消耗大','行业薪资较低，顶级公司才能提供竞争力薪酬','动物疫情风险不可预测，工作压力大'],
    'verdict':'就业稳定但工作艰苦。适合对畜牧业有热情、不畏艰苦环境的学生。'},
'Architecture':{
    'pros':['注册建筑师证书含金量高，职业路径明确','城市更新、老城改造带来持续需求','创意型岗位，设计自由度较高'],
    'cons':['地产行业下行周期影响较大','注册建筑师证书考取周期长，难度高','项目驱动型就业，市场波动时收入不稳定'],
    'verdict':'长期价值高但短期受地产周期影响。考证路径漫长，适合有建筑设计热情且耐得住寂寞的学生。'},
'Astronomy':{
    'pros':['空间科学战略升级，科研经费大幅增加','顶级数据分析能力让你在任何行业脱颖而出','学术成就国际认可度高'],
    'cons':['就业岗位极少，竞争激烈','纯学术路径需要博士及以上学历','转行需要额外积累实践能力'],
    'verdict':'学科价值极高但就业面极窄。适合确定走科研路线的顶尖学生。跨行需要主动转型。'},
'Atmospheric Sciences':{
    'pros':['气象局和环保部门就业稳定，编制机会多','气候变化全球热点，研究和咨询需求扩大','防灾减灾体系建设持续投入'],
    'cons':['纯研究岗位竞争激烈','基层气象站工作条件相对艰苦','社会认知度有限，求职路径较窄'],
    'verdict':'进入气象系统路径清晰，工作稳定。有志于气候研究的学生可以选择，需接受可能的驻外条件。'},
'Automation':{
    'pros':['工业4.0核心专业，制造业智能化改造需求旺盛','机器人和智能装备产业高速增长','横跨制造、能源、交通多行业，就业面宽'],
    'cons':['基础薪资低于计算机','硬件软件交叉，学习曲线陡峭','传统工厂岗位正被更高端自动化岗位淘汰'],
    'verdict':'工业智能化的支柱专业。薪资不及软件但工作有保障，适合对机电系统感兴趣的学生。'},
'Basic Medical Sciences':{
    'pros':['生物医药产业崛起，基础研究转化价值大幅提升','新药研发、精准医学方向需求爆发','国家对医学基础研究投入持续增加'],
    'cons':['需要博士学历才有竞争力','学术内卷严重','从研究到应用周期长，短期回报有限'],
    'verdict':'生物医药时代的核心基础专业。需要深造才能发挥价值，适合立志做科研的学生。'},
'Biological Sciences':{
    'pros':['合成生物学、基因编辑前沿领域投资爆发','AI+生物交叉领域需求急剧增长','农业育种、工业微生物等应用场景广'],
    'cons':['本科就业压力较大，多数需要深造','生物行业薪资分层严重','产业化落地周期长'],
    'verdict':'未来感强的专业，但本科阶段就业困难。建议明确升学路径，深造后回报可观。'},
'Biomedical Engineering':{
    'pros':['医疗设备国产替代是国家战略，行业高速增长','AI医疗影像和机器人手术新兴岗位需求旺盛','交叉背景可跨工程与医学两个领域'],
    'cons':['知识体系宽泛，需同时深耕工程和医学','监管审批流程复杂，落地周期长','需追踪快速迭代的医疗法规'],
    'verdict':'医工交叉的热门方向，市场需求真实。但学习难度大，需要同时掌握两个专业领域。'},
'Business Administration':{
    'pros':['就业面广，几乎所有行业都需要管理人才','晋升路径清晰，从管培生到管理层成熟','可结合行业知识形成复合竞争力'],
    'cons':['通用型人才竞争激烈，本科起点溢价有限','薪资增长较慢，初期与技术岗位差距大','AI大量替代中层管理和分析工作'],
    'verdict':'万金油专业，就业不愁但起步薪资普通。需要尽早积累行业专业知识或去顶尖公司才能脱颖而出。'},
'Chem Engineering & Pharmacy':{
    'pros':['新能源材料、半导体化工需求拉动行业高速增长','制药工业规模庞大，合规化工人才需求持续','工程师持证上岗，门槛提供一定保护'],
    'cons':['化工行业公众形象受限，优质项目选址受限','部分工种存在职业健康风险','薪资随大宗商品价格波动较大'],
    'verdict':'新能源和制药双引擎带动，前景改善中。工作环境是现实考量，建议选择合规大型企业。'},
'Chemistry':{
    'pros':['新材料、新能源、生物医药均以化学为基础','企业应用化学研发岗位稳定','中学化学教师需求稳定'],
    'cons':['本科单纯化学就业较难，竞争力不足','科研路径竞争内卷严重','化工环境问题影响行业招募'],
    'verdict':'基础学科，深造后出路宽广。本科阶段需要主动结合应用方向或考取教师资格。'},
'Chinese Language & Lit':{
    'pros':['传媒、教育、出版三大行业的基础专业','AI内容工具的提示词工程和文案优化需求增长','中国文化输出加速，汉语教学需求双增'],
    'cons':['本科就业竞争激烈，薪资普遍偏低','传统媒体萎缩，纸媒岗位持续缩减','AI冲击初级写作和编辑岗位'],
    'verdict':'文化产业和教育领域的基础专业。竞争激烈，但善用AI工具者有机会。建议复合技能发展。'},
'Chinese Materia Medica':{
    'pros':['国家大力振兴中医药，政策扶持力度空前','中药制药工业规模持续扩大','大健康产业高速增长，养生调理市场庞大'],
    'cons':['监管持续收紧，中药标准化要求提高','中药材质量参差不齐，品控难度大','国际认可度有限'],
    'verdict':'政策红利明显的专业。适合认同中医药价值体系的学生，需关注监管趋严带来的机遇与挑战。'},
'Civil Engineering':{
    'pros':['基础设施建设体量巨大，传统就业规模稳定','注册建造师等证书保护力强','城市更新带来持续需求'],
    'cons':['地产行业深度调整，毕业生就业压力上升','工地一线工作条件艰苦，晋升依赖资历','BIM和AI冲击传统设计和造价岗位'],
    'verdict':'传统大专业，规模大但竞争激烈。证书是核心竞争力，深耕技术路线仍有稳定出路。'},
'Clinical Medicine':{
    'pros':['AI难以替代人文关怀和临床判断，稳定性极强','执业医师证提供强力门槛保护','薪资随年资大幅提升，高年资专科医生收入丰厚'],
    'cons':['培养周期极长，5年本科+3年规培，经济回报慢','工作强度大，医患矛盾是现实压力','考研考执照竞争激烈，投入成本高'],
    'verdict':'最稳定的高价值专业之一，但前期投入巨大。需要强烈的从医意愿和对长期回报的耐心。'},
'Computer Science':{
    'pros':['AI时代核心专业，需求爆发式增长','起薪高，头部互联网公司校招待遇优厚','远程就业灵活，全球岗位均可申请'],
    'cons':['35岁焦虑问题是行业共识','知识迭代速度极快，需要持续学习','裁员周期出现时波动较大'],
    'verdict':'当代最强就业专业。竞争激烈但需求旺盛，适合有逻辑思维、能持续学习的学生。'},
'Crop Production':{
    'pros':['粮食安全国家战略，涉农专业政策扶持强','生物育种等前沿方向投资大','农业龙头企业提供高薪岗位'],
    'cons':['基层农技推广岗位薪资偏低','田间工作对身体要求较高','就业地点多为农业区'],
    'verdict':'国家粮食安全的基础专业。高端育种和农业科技方向有好出路，基层工作需心理准备。'},
'Dental Medicine':{
    'pros':['口腔医疗市场化程度高，民营诊所薪资丰厚','口腔科医患关系相对和谐','消费升级推动正畸种植市场高速增长'],
    'cons':['学制长，市场对经济波动有一定敏感性','设备技术更新快，持续学习成本高','开诊所创业需要大量前期资本'],
    'verdict':'口腔医学是医学中市场化程度最高的方向，高年资医生收入丰厚。值得选择，但需做好长周期深造的准备。'},
'E-Commerce':{
    'pros':['跨境电商市场持续高速增长，复合人才稀缺','直播电商等新业态不断涌现','平台型企业和自主品牌均有大量需求'],
    'cons':['岗位容易被数据分析工具和AI替代','行业变化快，专业知识快速过时','创业竞争异常激烈，头部效应明显'],
    'verdict':'增长赛道，但门槛低竞争激烈。需要持续跟上平台规则变化，结合数据分析技能竞争力更强。'},
'Economics':{
    'pros':['政府和金融机构持续招募经济分析人才','研究生升学路径宽广','数字经济、碳市场等新兴方向需求增大'],
    'cons':['本科就业相对困难，薪资优势不突出','量化工具正替代传统经济分析岗位','纯理论与产业结合较弱'],
    'verdict':'升学和转行都有路径，但直接就业不占优势。建议结合编程和数据分析技能。'},
'Education':{
    'pros':['教师编制提供极强的就业稳定性','教育科技公司快速扩张','政策持续推动教育投入'],
    'cons':['公立体制内薪资增长缓慢','双减政策后课外培训行业大幅萎缩','AI辅助学习工具冲击传统辅导岗位'],
    'verdict':'教师职业稳定性强，是许多家庭的首选。但薪资天花板较低，需要有从教的热情。'},
'Electrical Engineering':{
    'pros':['新能源革命推动电力系统全面升级，需求爆发','电网和新能源央企提供稳定就业','电气工程师证提供职业门槛'],
    'cons':['电力系统工作轮班、驻场要求多','技术学习曲线陡峭','传统火电厂岗位逐步缩减'],
    'verdict':'新能源时代最受益的传统工科之一。国有电力企业就业稳定，新能源方向薪资可观。'},
'Electronic Information':{
    'pros':['半导体国产替代是国家战略，人才缺口巨大','5G、物联网、自动驾驶全面驱动需求','平均薪资在工科专业中名列前茅'],
    'cons':['芯片设计学习门槛高，知识体系复杂','受地缘政治影响较大','顶级岗位集中于少数头部企业'],
    'verdict':'最受国家战略支撑的工科专业。人才缺口真实，但进入顶级企业需要强劲的技术实力。'},
'Energy & Power':{
    'pros':['双碳目标推动能源行业全面转型，机会大','新能源央企大规模招募工程技术人才','储能技术岗位需求快速增长'],
    'cons':['传统煤电岗位持续减少','新能源项目出差和驻场多','薪资增长相对IT慢'],
    'verdict':'转型期的专业，新能源方向需求旺盛。传统能源方向需要提早规划转型。'},
'Environmental Engineering':{
    'pros':['碳中和政策推动大量绿色就业岗位','环保督察常态化，合规人才需求持续','国际化机会多'],
    'cons':['环保咨询行业竞争激烈，薪资较低','政策变化对就业方向影响较大','重度现场工作，体力和心理要求高'],
    'verdict':'政策支持明显的专业，但薪资与预期可能有落差。结合数据分析或碳市场方向竞争力更强。'},
'Ethnology':{
    'pros':['国家民族政策研究需求稳定','少数民族文化传承与保护项目增多','跨文化研究国际合作机会丰富'],
    'cons':['就业面极窄，主要集中于政府和少数高校','薪资水平偏低','田野调查常驻偏远地区'],
    'verdict':'就业面窄，适合有强烈民族学研究热情的学生。大多数人需要结合公考或转向相关领域。'},
'Finance':{
    'pros':['金融是经济体系核心，需求长期稳定','顶级金融机构薪资丰厚','数字金融、绿色金融等新赛道机会大'],
    'cons':['受经济周期和政策影响波动明显','顶级岗位竞争激烈，学历要求高','AI量化工具替代大量初中级分析岗位'],
    'verdict':'高薪但高压的专业。顶级机构名校学历门槛高，但中等机构仍有大量需求。'},
'Fisheries':{
    'pros':['水产品出口规模庞大，相关企业需求持续','深远海养殖等新模式资本密集','食品安全监管推动水产检验岗位增加'],
    'cons':['从业环境辛苦，海上作业有安全风险','薪资水平与环境相比回报有限','水产病害风险难以完全预测'],
    'verdict':'食品安全领域的基础专业，就业稳定但环境艰苦。适合有水产业兴趣的学生。'},
'Food Science & Engineering':{
    'pros':['食品工业是国民基础行业，市场规模庞大','功能性食品、预制菜等细分赛道快速崛起','食品安全监管机构持续扩编'],
    'cons':['食品企业利润率偏低，薪资竞争力有限','研发投入相对较低','食品安全事故对职业声誉有影响'],
    'verdict':'就业稳定但薪资普通。进入大型食品企业或外资品牌研发部门是较好出路。'},
'Foreign Languages':{
    'pros':['高水平翻译和跨文化管理需求随国际化增加','一带一路小语种需求快速增长','语言学在AI训练数据和本地化领域需求扩大'],
    'cons':['机器翻译快速提升，初级笔译岗位大幅压缩','同声传译等高端岗位门槛极高','纯语言背景就业竞争力相对有限'],
    'verdict':'语言+专业的组合才是核心竞争力。单纯英语已不够，建议同时深耕某个领域。小语种有稀缺价值。'},
'Forensic Medicine':{
    'pros':['司法体制需求稳定','高度专业化，AI难以替代实体鉴定','从事法医工作具有特殊社会意义'],
    'cons':['工作内容压力大，心理承受要求高','就业集中于司法机关','工作强度与薪资性价比一般'],
    'verdict':'高度稳定的小众专业。适合心理素质过硬、认同法医工作价值的学生。'},
'Forestry':{
    'pros':['碳汇森林项目推动林业价值大幅提升','国家储备林工程带来大量就业','生态修复国际合作机会多'],
    'cons':['山区林场工作条件艰苦','薪资水平在工科中偏低','信息化改造步伐相对缓慢'],
    'verdict':'生态文明建设背景下价值提升。工作环境是主要考量，适合热爱自然、愿意扎根林区的学生。'},
'Forestry Engineering':{
    'pros':['木材工程、生物质能源方向具有一定稀缺性','国家储备林项目资金充裕','家具制造业升级带动木材技术需求提升'],
    'cons':['就业地点偏远，城市机会少','行业整体薪资水平有限','传统加工业受自动化冲击较大'],
    'verdict':'就业稳定但薪资和地点是现实考量。家具设计和林产化工方向可以结合创意产业。'},
'Geographic Sciences':{
    'pros':['国土调查和城市规划需求持续，政府岗位稳定','遥感和GIS与大数据结合形成新兴岗位','测绘资质有明确执业壁垒'],
    'cons':['纯地理方向就业不如GIS好','学习内容广但专精度不足','政府岗位薪资有限'],
    'verdict':'GIS和遥感方向就业较好，建议向空间数据分析方向深化。地理教师是稳定路径。'},
'Geology':{
    'pros':['矿产资源和能源勘探对地质人才需求稳定','关键矿产战略地位提升，勘探投资加大','地质工程师证提供职业保护'],
    'cons':['野外工作艰苦，长期驻扎偏远地区','行业随矿业周期波动','城市岗位较少'],
    'verdict':'就业有保障但生活条件艰苦。关键矿产时代有新机遇，适合不惧野外工作的学生。'},
'Geology Engineering':{
    'pros':['基础设施建设中地质勘察不可缺少','地下空间开发等新方向投资大','注册地质工程师证书竞争性强'],
    'cons':['工作多在野外或工程现场','行业薪资随项目周期波动','行业吸引力有限，竞争压力相对缓和'],
    'verdict':'基础设施建设的必需专业，证书是核心资产。野外工作是必须接受的代价。'},
'Geophysics':{
    'pros':['油气勘探和地震监测对地球物理人才需求稳定','深部地球探测纳入国家战略','数据科学技能结合后溢价高'],
    'cons':['就业集中于少数油气企业和科研院所','油价下跌直接影响行业招聘','工作多在野外勘探'],
    'verdict':'专业性强，就业集中。建议结合机器学习和数据处理技能，提高跨行业竞争力。'},
'Grassland Science':{
    'pros':['荒漠化治理和草地修复是国家重大生态工程','草地碳汇进入碳市场带来新价值','牧区政策扶持有生活补贴'],
    'cons':['就业集中于欠发达草原地区','薪资普遍偏低，与城市落差大','行业规模小，岗位数量少'],
    'verdict':'小众且地域性强的专业。适合有草原情怀、能接受艰苦条件的学生，生态修复方向有一定发展空间。'},
'History':{
    'pros':['文化产业快速发展，历史研究商业化机会增多','博物馆和文物保护机构需求稳步增加','历史思维在政策研究中有独特价值'],
    'cons':['学术职位极度稀缺，竞争异常激烈','非学术路径需要大幅度转型','薪资水平普遍偏低'],
    'verdict':'人文底蕴深厚但就业面窄。博物馆、传媒、文化产业是主要出路，需主动拓展就业边界。'},
'Hydraulic Engineering':{
    'pros':['水利基础设施投资持续，大工程带来需求','防洪减灾系统建设需求大','注册水利工程师证书有职业保护'],
    'cons':['工程建设周期长，岗位与项目绑定','部分工程地处偏远地区','薪资增速慢于IT行业'],
    'verdict':'国家水利基础设施的支撑专业。收入稳定，晋升依赖资历，适合有长期规划的学生。'},
'Industrial Engineering':{
    'pros':['制造业精益化改造需求旺盛，专家稀缺','供应链优化和智能仓储人才需求大','横跨制造与管理，晋升路径多样'],
    'cons':['部分工作内容枯燥，改善周期长','不结合数据分析则竞争力有限','薪资增长相对缓慢'],
    'verdict':'制造业升级的支柱专业，结合数字化能力竞争力强。建议积极考取精益六西格玛等证书。'},
'Instrumentation':{
    'pros':['高端仪器设备国产替代是战略方向，需求爆发','精密制造、航空航天、医疗设备均需此专业','细分领域技术壁垒高'],
    'cons':['行业知名度低，求职时需要主动介绍专业','顶级企业集中在少数城市','硬件开发周期长，迭代慢于软件'],
    'verdict':'小众但稀缺的高端制造专业。国产替代战略带来历史性机遇，适合有工匠精神的学生。'},
'Integrative Medicine':{
    'pros':['政府大力推广中西医协同诊疗模式','高水平中西医结合人才极度稀缺','在肿瘤辅助治疗等领域有独特价值'],
    'cons':['需同时学习中西两套体系，学习负担极重','职业认可度在不同医院间差异大','临床科研双轨，时间压力大'],
    'verdict':'稀缺的交叉医学人才。学习强度极大，但成功者在顶级医院有独特竞争力。'},
'Interdisciplinary Eng':{
    'pros':['新兴技术领域几乎都是交叉学科，先发优势明显','量子计算、脑机接口等前沿稀缺人才','学科边界处往往隐藏最大创新机会'],
    'cons':['在单学科中可能不如专业人才深厚','就业市场对交叉背景认知有限','学习路径不清晰，自我定向能力要求高'],
    'verdict':'面向未来的探索型专业。适合有强烈求知欲、善于自我定向的学生，需要主动创造就业价值。'},
'Intl Economics & Trade':{
    'pros':['跨境贸易、外资利用领域持续有稳定需求','贸易合规、出口管制等专业岗位薪资提升','双语能力和国际规则知识有综合竞争力'],
    'cons':['通用性较强但缺乏核心技术壁垒','地缘政治变化对贸易政策影响波动大','AI替代大量基础外贸文档处理工作'],
    'verdict':'国际化时代的稳定专业，但需要结合行业专长才能脱颖而出。贸易合规方向是新的增长点。'},
'Journalism & Comm':{
    'pros':['全媒体转型带来短视频、直播等新内容岗位','企业品牌传播和公关岗位需求稳定','优质内容创作者仍有高变现可能'],
    'cons':['传统媒体萎缩，招聘持续减少','AI批量生成内容冲击初级写作','行业薪资分化严重'],
    'verdict':'传统路径萎缩，新媒体路径崛起。关键是掌握数字运营能力和特定垂直领域的深度内容生产能力。'},
'Law':{
    'pros':['执照保护职业门槛，法律服务需求稳定','公司法务、合规与知识产权方向薪资可观','数字经济AI法律问题带来大量新业务'],
    'cons':['顶级律所竞争激烈，需要名校和持续高强度工作','基层岗位收入偏低','AI工具在文件审查方面冲击明显'],
    'verdict':'长期稳定的专业，合规和企业法务方向需求增长。选择法学需要明确路径规划，考证是核心。'},
'Library & Info Management':{
    'pros':['数字图书馆和知识管理平台需求增加','信息架构在企业中价值提升','政府档案和记录管理体系扩张'],
    'cons':['传统图书馆编制岗位减少','岗位晋升空间受限于机构规模','数字化转型中不确定性增加'],
    'verdict':'信息管理方向转向数字化后有新机会。适合喜欢信息组织和知识管理的学生。'},
'Light Industry':{
    'pros':['消费升级带动食品、纸张、日化品质提升需求','包装设计与环保材料方向有新机会','外资日化和快消品公司提供稳定就业'],
    'cons':['行业利润率偏低，薪资竞争力较弱','自动化替代传统流水线工作','品牌溢价主要被外资品牌获取'],
    'verdict':'就业稳定但薪资普通。进入外资快消品公司研发或品牌方向是较好出路。'},
'Logistics Management':{
    'pros':['电商生态系统带动物流行业高速增长','冷链、跨境物流等细分赛道专业人才稀缺','物流科技投资拉动智能仓储和无人配送需求'],
    'cons':['基层岗位体力要求高，晋升路径不够清晰','不与互联网结合则竞争力有限','物流管理软件逐步替代人工调度'],
    'verdict':'电商和供应链时代需求旺盛。结合数字化和供应链优化能力是核心竞争力。'},
'Management Sci & Eng':{
    'pros':['融合管理学、数学和计算机，就业面广','数据驱动的管理决策需求大幅提升','咨询、互联网、金融均有大量需求'],
    'cons':['定位模糊，需靠个人能力突围','与纯计算机相比，技术深度可能不足','薪资依具体岗位差异较大'],
    'verdict':'复合型专业，灵活性强。建议尽早锚定某个行业方向，结合量化或技术能力形成差异化优势。'},
'Marine Sciences':{
    'pros':['蓝色经济战略下海洋科研和开发投资大幅增加','深海探测和海洋能源开发方向发展快','气候研究对海洋观测人才需求上升'],
    'cons':['高级职位集中于少数机构','海上野外工作条件艰苦','就业主要在沿海城市'],
    'verdict':'蓝色经济时代价值提升。科研路径需要深造，应用方向可在沿海产业找到出路。'},
'Materials Science':{
    'pros':['半导体、新能源电池、航空航天均依赖材料突破','政策大力扶持新材料产业','产学研结合紧密，科研成果转化路径成熟'],
    'cons':['实验周期长，研究成果见效慢','传统冶金受自动化冲击较大','就业分散在多个行业，专业品牌不够突出'],
    'verdict':'新材料时代的战略专业。需要明确方向，半导体材料和电池材料是最值得投入的细分。'},
'Mathematics':{
    'pros':['数据科学、量化金融、AI研发均以数学为基础','考研和读博升学优势明显','思维训练是所有高薪岗位的底层能力'],
    'cons':['本科阶段直接就业较困难','偏纯理论方向需要深造才有竞争力','部分应用方向会被算法工具替代'],
    'verdict':'最强的基础学科之一，深造后回报极高。建议本科阶段同时学习编程，为金融或AI方向打好基础。'},
'Mechanical Engineering':{
    'pros':['制造业核心专业，需求稳定且规模大','智能制造、新能源汽车等方向吸纳大量毕业生','执业证书提供一定保护'],
    'cons':['薪资增速慢于软件','传统设计岗位正被AI辅助设计软件替代','一线工程师工作环境相对艰苦'],
    'verdict':'制造强国的基础专业，规模大但溢价有限。新能源汽车和智能制造方向是高薪突破口。'},
'Mechanics':{
    'pros':['航空、航天、大型工程项目均需力学支撑','数值模拟与计算力学是高端工程岗位核心','读博科研路径清晰'],
    'cons':['纯力学就业面相对较窄','本科需要深造才能找到对口优质工作','社会认知度有限'],
    'verdict':'硬核基础工程学科。深造后在航空航天、汽车碰撞仿真等方向有独特价值。'},
'Medical Technology':{
    'pros':['医疗检验、影像、康复等技术岗位需求稳定','医疗设备更新推动技术升级','培养周期比临床医生短，更快独立工作'],
    'cons':['执行性岗位居多，薪资不及临床医生','晋升路径有限，主要靠技术专精','AI影像诊断对技术岗位有中长期压力'],
    'verdict':'医疗行业的技术支柱，就业稳定。薪资不高但工作相对规律，是进入医疗行业的务实路径。'},
'Mining':{
    'pros':['关键矿产战略地位提升，锂钴稀土开采需求大','资源类央企招聘稳定，待遇较好','海外矿山项目薪资溢价明显'],
    'cons':['工作环境危险，矿山安全风险不可忽视','受大宗商品价格周期影响','年轻人入行意愿低'],
    'verdict':'关键矿产时代有战略价值，但工作环境是真实挑战。愿意接受野外和高风险工作的学生有很好出路。'},
'Nature Conservation & Ecology':{
    'pros':['生物多样性保护纳入国家考核，岗位需求增加','国际环保组织有稳定岗位','生态系统服务价值化为自然资本开发提供路径'],
    'cons':['高等级岗位集中在少数顶级机构','野外调查工作艰苦，薪资回报有限','国内商业化路径尚不成熟'],
    'verdict':'有情怀的专业，就业面较窄。结合GIS和数据分析技能，在政府和国际机构有较好出路。'},
'Nuclear Engineering':{
    'pros':['国家大规模新建核电站，人才缺口极大','进入壁垒高，薪资远超普通工程师','核安全要求严格，稳定性极强'],
    'cons':['就业集中于少数核电企业和军工单位','涉密程度高，职业流动受限','部分公众对核能有顾虑'],
    'verdict':'高度稀缺的战略专业。薪资丰厚，就业极稳，但职业路径单一。适合愿意长期深耕核领域的学生。'},
'Nursing':{
    'pros':['老龄化社会推动护理需求快速增长','国际护理资格可移民海外','专科护理薪资显著高于普通护士'],
    'cons':['工作强度大，三班轮岗身体消耗大','社会地位有待提升','公立医院薪资受绩效制约'],
    'verdict':'需求持续增长的民生专业。工作艰辛但价值重要，海外路径是高效跃升的选择。'},
'Ocean Engineering':{
    'pros':['海上风电、深海油气平台方向投资大幅增加','蓝色经济战略提升行业地位','海洋探测装备国产化需求迫切'],
    'cons':['海上作业条件艰苦，安全风险高','行业规模有限，岗位集中在沿海城市','受油价波动影响较大'],
    'verdict':'蓝色经济战略下的新兴工科。海上风电方向是未来重点，海洋装备国产化带来机遇。'},
'Ocean Sciences':{
    'pros':['深海探测战略带来科研经费增加','海洋气候研究与防灾减灾需求扩大','国际研究合作机会丰富'],
    'cons':['纯学术路径竞争激烈，需要博士学历','就业集中于少数海洋研究机构','野外作业条件艰苦'],
    'verdict':'学科价值真实但就业面窄。深造后在海洋研究机构或海洋产业有位置，一般本科难以直接就业。'},
'Ordnance':{
    'pros':['国防科工体系稳定招募，福利待遇好','军工企业技术保密，竞争相对封闭','薪资随级别晋升提升'],
    'cons':['就业集中于军工央企，选择面窄','涉密限制职业流动性','部分单位地处偏远地区'],
    'verdict':'国防科工行业稳定且具保密待遇，适合认同国防事业的学生。职业流动性较低需提前了解。'},
'Pharmacy':{
    'pros':['创新药研发是国家战略，生物制药资本密集','执业药师证提供就业门槛保护','医院药学、医药电商需求持续'],
    'cons':['新药研发周期长，风险高','药店零售岗位薪资较低','国内药学与国际顶尖水平仍有差距'],
    'verdict':'医药行业的支柱专业。创新药方向高薪但门槛高，执业药师路径稳定但薪资一般。'},
'Philosophy':{
    'pros':['AI伦理、科技与社会政策方向需求快速增长','逻辑训练在法律、咨询、战略分析领域独具价值','政策研究和智库有一定岗位需求'],
    'cons':['就业面极窄，直接对口岗位少','高级职位竞争激烈','薪资普遍偏低'],
    'verdict':'最具思维训练价值的基础学科之一，但直接就业极为困难。通常需要法学、经济学等方向深造才能落地。'},
'Physical Education':{
    'pros':['中小学体育教师需求随素质教育改革扩大','职业体育商业化，运动训练高管稀缺','大健康产业推动运动康复市场爆发'],
    'cons':['公立体育教师编制竞争激烈','职业运动员寿命短，需提前规划第二职业','部分商业体育岗位薪资不稳定'],
    'verdict':'体育产业快速发展的受益专业。教师路径稳定，运动康复和私人教练市场薪资可期。'},
'Physics':{
    'pros':['量子计算、半导体物理等硬科技方向需求大','物理思维让你在任何量化领域脱颖而出','国防、航天持续招募优秀物理人才'],
    'cons':['本科直接就业困难，几乎都需要深造','硬科技研究周期极长','转行商业领域需要额外积累'],
    'verdict':'最难也最有价值的基础学科。深造后在半导体、量化金融或AI领域有顶尖竞争力。需要做好长期投入的准备。'},
'Political Science':{
    'pros':['政府部门、国有机构、国际组织均有需求','政策研究和国际关系分析岗位稳定','适合外交和涉外企业方向'],
    'cons':['路径较为单一，主要集中在体制内','晋升速度慢，依赖年资积累','薪资较低但工作稳定'],
    'verdict':'体制内路径清晰。对进入政府、国有企业或外交系统有明确规划的学生适合选择。'},
'Psychology':{
    'pros':['心理健康意识快速上升，市场需求爆发','企业EAP和学校心理健康需求大','大数据与心理学结合形成新兴用户研究方向'],
    'cons':['执照获取困难，心理咨询师认证门槛高','本科阶段就业困难','市场乱象较多'],
    'verdict':'需求真实快速增长的专业。本科就业有挑战，需要持证才能从事咨询，用户研究方向是较好的跨行选择。'},
'Public Administration':{
    'pros':['公务员考试是重要出路，编制稳定','政府数字化带来新型公共管理岗位','政策研究、智库非政府路径需求增加'],
    'cons':['公务员竞争激烈，上岸率低','薪资增长受职级限制','传统行政流程正被数字化工具替代'],
    'verdict':'适合有公务员从业意向的学生，就业路径清晰，但竞争激烈。体制外路径需要主动开拓。'},
'Public Finance':{
    'pros':['财政预算、国资管理是政府职能核心岗位','政府审计和财政监督改革带来需求','财政数字化推动新岗位'],
    'cons':['路径高度集中于政府和国有机构','薪资受公务员体系限制','政策不确定性存在'],
    'verdict':'适合立志进入财政、审计或国资体系的学生。职业稳定，但薪资上限有限。'},
'Public Health':{
    'pros':['疫情后公共卫生体系建设投资大幅增加','流行病学和卫生政策分析需求持续','WHO等国际组织的稳定岗位'],
    'cons':['疾控系统薪资长期偏低','突发公共卫生事件工作强度极高','转入私营机构难度较大'],
    'verdict':'社会价值极高但薪资偏低的专业。有强烈社会责任感和对公共卫生有热情的学生适合选择。'},
'Safety Engineering':{
    'pros':['安全生产法规严格执行带动需求','注册安全工程师证书提供职业门槛','应急管理体系扩建，相关岗位增加'],
    'cons':['基础岗位薪资偏低','工作压力大，事故责任风险高','部分高危行业一线条件艰苦'],
    'verdict':'政策驱动的必需专业。证书和经验是核心资产，适合注重安全和责任的学生。'},
'Semiconductor':{
    'pros':['芯片国产化战略推动行业高速增长，人才极度稀缺','薪资在所有工程学科中名列前茅','晶圆厂和设计公司均提供丰厚待遇'],
    'cons':['技术门槛极高，学习周期长','芯片研发失败率高，迭代压力大','岗位垄断于少数顶级企业'],
    'verdict':'当前最受国家战略支持的工科专业。人才缺口极大，薪资丰厚，但需要极强的技术能力。'},
'Sociology':{
    'pros':['UX研究、用户洞察、政策评估方向需求增加','跨学科能力让你在多个行业有竞争力','社会创新和NGO领域有稳定人才缺口'],
    'cons':['本科就业直接对口岗位少，薪资偏低','需结合定量技能才有竞争力','高校职位极度稀缺'],
    'verdict':'思维灵活但就业路径需要主动规划。结合R/Python等数据分析工具，用户研究方向竞争力较强。'},
'Statistics':{
    'pros':['数据时代最具普适性的专业之一，就业面极广','金融、互联网、医药均需统计人才','研究生升学极为顺利'],
    'cons':['本科阶段需结合计算机技能才能竞争','基础统计岗位正被自动化工具替代','金融方向竞争激烈'],
    'verdict':'黄金时代的基础专业。结合Python和机器学习能力后就业面大幅扩大，建议本科阶段同步学习编程。'},
'Surveying & Mapping':{
    'pros':['国土调查和城市三维建模需求持续','无人机+GIS带来新兴应用场景','注册测绘师执照提供职业壁垒'],
    'cons':['大量野外测量工作较为辛苦','数字化转型导致传统测绘岗位减少','薪资水平在工科中偏低'],
    'verdict':'专业壁垒清晰，执照价值稳定。数字化转型推动GIS+无人机方向，适合善于将技术与实地工作结合的学生。'},
'Trad. Chinese Medicine':{
    'pros':['中医热潮推动诊所和医院中医科扩容','国家大力推广中医药国际传播','民营中医诊所市场化程度高'],
    'cons':['执照获取难度高，资质要求严格','循证证据积累不足，学术认可度有限','患者接受度受地区和年龄影响'],
    'verdict':'文化认同度高、需求稳定的传统医学专业。市场需求真实，但需要较长时间才能形成稳定的患者基础。'},
'Textile':{
    'pros':['功能性纺织品和智能服装等高端方向市场增长','一带一路国家轻工业合作机会大','环保纤维和生物基材料是未来方向'],
    'cons':['传统纺织厂自动化替代工人加速','行业重心向东南亚迁移，国内就业规模缩小','品牌溢价主要集中在少数设计和奢侈品企业'],
    'verdict':'转型期的传统专业。高端功能纺织和可持续材料方向有新机会，普通纺织岗位则面临压缩。'},
'Tourism Management':{
    'pros':['旅游市场疫后强劲复苏，文旅消费激增','文化旅游与乡村振兴结合，新业态多','高星级酒店管理培训体系成熟'],
    'cons':['行业受政策和突发事件影响波动大','基层服务岗位薪资偏低','数字平台压缩传统旅行社中间环节'],
    'verdict':'需求回暖但行业波动大。酒店管理和文旅运营方向有较好出路，建议争取国际品牌酒店实习资源。'},
'Transportation':{
    'pros':['高铁、航运、航空规模扩大带来稳定就业','智能交通推动专业升级','行业资质有明确壁垒'],
    'cons':['部分岗位生活规律性差','薪资随企业差异较大','自动驾驶对驾驶类岗位有长期冲击'],
    'verdict':'基础设施的核心专业，就业稳定。航空飞行技术方向薪资极高但选拔严苛，其他方向收入中等但稳定。'},
'Veterinary Medicine':{
    'pros':['宠物市场爆发，宠物医院全国快速扩张','食品检验检疫、动物防疫等政府岗位稳定','宠物专科执业兽医收入快速提升'],
    'cons':['执业兽医资格考试难度高','动物疫情处置工作风险高、压力大','公立单位薪资偏低'],
    'verdict':'宠物经济和食品安全双驱动的专业。私立宠物医院薪资快速提升，公立防疫岗位稳定，两条路径都值得考虑。'},
}
